@startuml
'https://plantuml.com/class-diagram

title Java Time

'时间单位
interface TemporalUnit

enum ChronoUnit {}

TemporalUnit <|-- ChronoUnit


'日期或时间的字段
interface TemporalField {
    TemporalUnit getBaseUnit()

    boolean isDateBased()
    boolean isTimeBased()
}

enum ChronoField {}

TemporalField <|-- ChronoField


interface TemporalAmount {}

class Duration {
}

TemporalAmount <|-- Duration


'日期和时间对象的只读访问接口
interface TemporalAccess {
    boolean isSupported(TemporalField field)
    long getLong(TemporalField field)
    int get(TemporalField field)
}

'时间调整器
interface TemporalAdjuster {
    Temporal adjustInto(Temporal source)
}

interface Temporal {
    boolean isSupported(TemporalUnit unit)
    Temporal with(TemporalAdjuster adjuster)

    Temporal plus(TemporalAmount amount)
    Temporal plus(long amountToAdd, TemporalUnit unit)

    Temporal minus(TemporalAmount amount)
    Temporal minus(long amountToSubtract, TemporalUnit unit)

    long until(Temporal endExclusive, TemporalUnit unit)
}

TemporalAccess <|-- Temporal



class LocalTime {
}

Temporal <|-- LocalTime
TemporalAdjuster <|-- LocalTime

''''''''''''''' 时区相关 '''''''''''''''

abstract class ZoneId {
}

class ZoneOffset {
}

ZoneId <|-- ZoneOffset


''''''''''''''' 时刻相关 '''''''''''''''

abstract class Clock {
}

'时刻
class Instant {

}

'聚合。Instant 通常基于 Clock 创建的
Clock o--> Instant

Temporal <|-- Instant
TemporalAdjuster <|-- Instant

@enduml